name: Automated Testing
on:
  push:
    branches: [ master, kycio-test ]
  pull_request:
    branches: [ master ]

jobs:
  automated-testing-selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run automated testing
        run: mvn clean install --file kycio-test/pom.xml

